# Generated by Django 5.0.4 on 2024-04-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Account', max_length=200, unique=True)),
                ('password', models.CharField(default='Password', max_length=200)),
                ('logged_in', models.BooleanField(default='False')),
                ('auth_token', models.CharField(default='e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', max_length=200)),
            ],
        ),
    ]
